runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /python
  script: main.app

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)